# Generated by Django 5.2.8 on 2025-12-08 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("expected_output", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("duration_days", models.IntegerField(editable=False, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accountable_person",
                    models.ForeignKey(
                        help_text="Primary person accountable for project success (RACI: Accountable)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accountable_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[("file", "File Upload"), ("link", "External Link")], max_length=10
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="projects/materials/%Y/%m/"),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("link_title", models.CharField(blank=True, max_length=255, null=True)),
                ("link_url", models.URLField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_material",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                (
                    "duration_template",
                    models.CharField(
                        blank=True, help_text="e.g., '3 months'", max_length=100, null=True
                    ),
                ),
                (
                    "sprint_goals",
                    models.TextField(
                        blank=True, help_text="Describe the main objectives", null=True
                    ),
                ),
                (
                    "expected_deliverables",
                    models.TextField(blank=True, help_text="List the key deliverables", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_sprint",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.sprint",
            ),
        ),
        migrations.CreateModel(
            name="ProjectComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment for threaded replies",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="projects.projectcomment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_comment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"], name="projects_co_project_6e0434_idx"
                    ),
                    models.Index(
                        fields=["parent", "-created_at"], name="projects_co_parent__417b3a_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="projects_co_user_id_ebaa2f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "raci_role",
                    models.CharField(
                        choices=[
                            ("R", "Responsible"),
                            ("A", "Accountable"),
                            ("C", "Consulted"),
                            ("I", "Informed"),
                        ],
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "projects_member",
                "indexes": [
                    models.Index(
                        fields=["project", "raci_role"], name="projects_me_project_030926_idx"
                    ),
                    models.Index(fields=["user"], name="projects_me_user_id_3e2856_idx"),
                ],
                "unique_together": {("project", "user", "raci_role")},
            },
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display order within project"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "projects_milestone",
                "ordering": ["project", "order", "due_date"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"], name="projects_mi_project_dc545b_idx"
                    ),
                    models.Index(
                        fields=["assigned_to", "due_date"], name="projects_mi_assigne_f1b9a4_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["start_date", "end_date"], name="projects_sp_start_d_3190a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sprint",
            index=models.Index(
                fields=["is_active", "department"], name="projects_sp_is_acti_403f96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "priority"], name="projects_pr_status_d9e5a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["accountable_person"], name="projects_pr_account_70daf4_idx"
            ),
        ),
    ]
