# Generated by Django 5.2.8 on 2026-01-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("manuscript", "Manuscript"),
                    ("dashboard", "Dashboard"),
                    ("analysis", "Analysis"),
                    ("review", "Review"),
                    ("data_collection", "Data Collection"),
                    ("administrative", "Administrative"),
                    ("other", "Other"),
                ],
                default="general",
                help_text="Category/type of activity",
                max_length=30,
            ),
        ),
    ]
