# Generated by Django 5.2.8 on 2026-01-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deliverables",
            field=models.TextField(
                blank=True,
                help_text="Expected outputs or deliverables for this project",
                null=True,
            ),
        ),
    ]
