# Generated by Django 5.2.8 on 2026-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="completed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
