# Generated by Django 5.2.8 on 2026-01-30 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_activity_completed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupervisorReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("started", "Review Started"),
                            ("completed", "Review Completed"),
                            ("rejected", "Rejected / Needs Revision"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="Review Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Review Started At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Review Completed / Closed At"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Supervisor Notes / Feedback"),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="True when review is completed or rejected",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Supervisor Review",
                "verbose_name_plural": "Supervisor Reviews",
                "db_table": "raci_supervisor_review",
                "ordering": ["-completed_at", "-started_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["project", "order", "-created_at"],
                "verbose_name": "RACI Activity",
                "verbose_name_plural": "RACI Activities",
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Display order within the project"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["project", "order"], name="raci_activi_project_ec24ee_idx"),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="activity",
            field=models.OneToOneField(
                help_text="The activity being reviewed (typically manuscript type)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_review",
                to="projects.activity",
            ),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewing Supervisor",
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorreview",
            index=models.Index(
                fields=["activity", "status"], name="raci_superv_activit_fd1f46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorreview",
            index=models.Index(fields=["supervisor"], name="raci_superv_supervi_639e96_idx"),
        ),
    ]
