# Generated by Django 5.2.8 on 2026-01-30 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_supervisorreview_alter_activity_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.UniqueConstraint(
                fields=("project", "order"), name="unique_activity_order_per_project"
            ),
        ),
    ]
