# Generated by Django 5.2.8 on 2026-02-03 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_useractivitypriority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supervisorreview",
            options={"ordering": ["-completed_at", "-started_at"]},
        ),
        migrations.RemoveIndex(
            model_name="supervisorreview",
            name="raci_superv_supervi_639e96_idx",
        ),
        migrations.RemoveField(
            model_name="supervisorreview",
            name="supervisor",
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="admin_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="is_admin_approved",
            field=models.BooleanField(blank=True, help_text="Admin approval decision", null=True),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="is_supervisor_approved",
            field=models.BooleanField(
                blank=True, help_text="Supervisor approval decision", null=True
            ),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="move_to_admin",
            field=models.BooleanField(
                default=False, help_text="Supervisor has escalated this review to Admin"
            ),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="review_level",
            field=models.CharField(
                blank=True,
                choices=[("supervisor", "Supervisor"), ("admin", "Admin")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewer",
            ),
        ),
        migrations.AddField(
            model_name="supervisorreview",
            name="supervisor_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supervisorreview",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_reviews",
                to="projects.activity",
            ),
        ),
        migrations.AlterField(
            model_name="supervisorreview",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supervisorreview",
            name="is_complete",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="supervisorreview",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="supervisorreview",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supervisorreview",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("started", "Review Started"),
                    ("completed", "Review Completed"),
                    ("reopened", "Reopened"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="supervisorreview",
            index=models.Index(fields=["reviewer"], name="raci_superv_reviewe_d1d950_idx"),
        ),
        migrations.AddConstraint(
            model_name="supervisorreview",
            constraint=models.UniqueConstraint(
                fields=("activity", "review_level"), name="unique_review_per_level"
            ),
        ),
    ]
