# Generated by Django 5.2.8 on 2026-02-05 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_supervisorreview_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("leave_pending", "Leave Pending Approval"),
                            ("leave_approved", "Leave Approved"),
                            ("leave_rejected", "Leave Rejected"),
                            ("activity_assigned", "Activity Assigned"),
                            ("activity_due", "Activity Due Soon"),
                            ("activity_overdue", "Activity Overdue"),
                            ("review_needed", "Review Needed"),
                            ("review_completed", "Review Completed"),
                            ("project_status", "Project Status Update"),
                            ("contract_expiring", "Contract Expiring"),
                            ("contract_expired", "Contract Expired"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("related_id", models.UUIDField(blank=True, null=True)),
                ("action_url", models.CharField(blank=True, max_length=500, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"], name="notificatio_recipie_201701_idx"
                    ),
                    models.Index(
                        fields=["is_sent", "retry_count"], name="notificatio_is_sent_cfeb95_idx"
                    ),
                ],
            },
        ),
    ]
