# Generated by Django 5.2.8 on 2026-02-05 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["project", "-created_at"],
                "verbose_name": "RACI Activity",
                "verbose_name_plural": "RACI Activities",
            },
        ),
        migrations.RemoveConstraint(
            model_name="activity",
            name="unique_activity_order_per_project",
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="raci_activi_project_ec24ee_idx",
        ),
        migrations.AlterField(
            model_name="activity",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, help_text="Display order within the project", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["project"], name="raci_activi_project_854a9d_idx"),
        ),
    ]
