# Generated by Django 5.2.8 on 2026-02-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_activityreview_activityreviewcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityreview",
            name="next_reviewer_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
