# Generated by Django 5.2.8 on 2026-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_activityreview_next_reviewer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityreview",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("started", "Started"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
