# Generated by Django 5.2.8 on 2026-01-12 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("fixed_term_locum", "Fixed Term (Locum Basis)"),
                            ("ftel", "FTE (Full-Time Equivalent)"),
                            ("annual", "Annual Contract"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_fte", models.BooleanField(default=False)),
                (
                    "fte_ratio",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("hours_per_week", models.DecimalField(decimal_places=2, max_digits=5)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "renewed_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renewals",
                        to="employee.employeecontract",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_contract",
                "ordering": ["-start_date", "-is_current"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSupervisor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_supervisors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervised_employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_supervisor",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("public", "Public Holiday"),
                            ("weekoff", "Week Off"),
                            ("company", "Company Holiday"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "employee_holiday",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["date", "holiday_type"], name="employee_ho_date_6eb552_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaveAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "annual_entitled",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("annual_earned", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "annual_carried_forward",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("annual_used", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("sick_entitled", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("sick_used", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "maternity_entitled",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("maternity_used", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "paternity_entitled",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("paternity_used", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "compassionate_entitled",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "compassionate_used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("study_entitled", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("study_used", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("other_entitled", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("other_used", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("carryforward_expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="employee.employeecontract"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_allocated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_leave_allocation",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("compassionate", "Compassionate Leave"),
                            ("study", "Study Leave"),
                            ("other", "Other"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                ("leave_type_other", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("num_days", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("programme_manager_approved", models.BooleanField(default=False)),
                ("programme_manager_approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisor_approved_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programme_manager_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pm_approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisors",
                    models.ManyToManyField(
                        blank=True, related_name="supervisor_selected", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_leave_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="employeecontract",
            index=models.Index(
                fields=["user", "is_current"], name="employee_co_user_id_cd8a4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeecontract",
            index=models.Index(
                fields=["start_date", "end_date"], name="employee_co_start_d_b85cef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveallocation",
            index=models.Index(fields=["user", "year"], name="employee_le_user_id_cc219a_idx"),
        ),
        migrations.AddIndex(
            model_name="leaveallocation",
            index=models.Index(fields=["contract"], name="employee_le_contrac_27b500_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="leaveallocation",
            unique_together={("user", "year", "contract")},
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["user", "status"], name="employee_le_user_id_148d73_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="employee_le_start_d_2e4886_idx"
            ),
        ),
    ]
