# Generated by Django 5.2.8 on 2026-01-15 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("annual_days", models.DecimalField(decimal_places=2, default=25, max_digits=6)),
                ("sick_days", models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ("maternity_days", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("paternity_days", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "compassionate_days",
                    models.DecimalField(decimal_places=2, default=5, max_digits=6),
                ),
                ("study_days", models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                (
                    "applies_to_gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        help_text="Leave this blank if applies to all genders",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "leave_group",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSupervisor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_supervisors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervised_employees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employee_supervisor",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("public_national", "Public Holiday (National)"),
                            ("public_global", "Public Holiday (Global)"),
                            ("administrative", "Administrative Holiday"),
                            ("weekoff", "Week Off"),
                            ("other", "Other"),
                        ],
                        default="public_national",
                        max_length=20,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "employee_holiday",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["date", "holiday_type"], name="employee_ho_date_6eb552_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("payroll_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("fixed_term_locum", "Fixed Term (Locum Basis)"),
                            ("fte", "FTE (Full-Time Equivalent)"),
                            ("annual", "Annual Contract"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_fte", models.BooleanField(default=False)),
                (
                    "fte_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="fte percentage proportion",
                        max_digits=6,
                    ),
                ),
                ("default_week_days", models.IntegerField(default=5)),
                ("contract_months", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("is_forfeited", models.BooleanField(default=False)),
                (
                    "annual_carried_forward",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual leave days carried forward from previous leave year",
                        max_digits=6,
                    ),
                ),
                (
                    "annual_leave_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual leave days already used before system tracking",
                        max_digits=6,
                    ),
                ),
                (
                    "sick_leave_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sick leave days already used before system tracking",
                        max_digits=6,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave entitlement group for this contract",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="employee.leavegroup",
                    ),
                ),
            ],
            options={
                "db_table": "employee_contract",
                "ordering": ["-start_date", "-is_current"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("compassionate", "Compassionate Leave"),
                            ("study", "Study Leave"),
                            ("other", "Other"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "days_requested",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Number of leave days (can be fractional for half days)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("supervisor_notes", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "programme_manager_approved",
                    models.BooleanField(
                        default=False, help_text="Whether programme manager has approved"
                    ),
                ),
                (
                    "programme_manager_approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Date when programme manager approved", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to="employee.employeecontract",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor assigned to approve this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leave_requests_to_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leave_request",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="employeecontract",
            index=models.Index(
                fields=["user", "is_current"], name="employee_co_user_id_cd8a4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeecontract",
            index=models.Index(
                fields=["start_date", "end_date"], name="employee_co_start_d_b85cef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeecontract",
            index=models.Index(fields=["payroll_number"], name="employee_co_payroll_e53def_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["user", "status"], name="leave_reque_user_id_598dad_idx"),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["supervisor", "status"], name="leave_reque_supervi_a12f45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="leave_reque_start_d_5cfac9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["leave_type", "status"], name="leave_reque_leave_t_a7383a_idx"
            ),
        ),
    ]
