# Generated by Django 5.2.8 on 2026-02-03 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="supervisors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Supervisors assigned to approve this request",
                related_name="leave_requests_to_approve",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor assigned to approve this request old",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_requests_to_approve_old",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
