# Generated by Django 5.2.8 on 2026-01-12 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaveallocation",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="leaveallocation",
            name="employee_le_user_id_cc219a_idx",
        ),
        migrations.RemoveField(
            model_name="employeecontract",
            name="hours_per_week",
        ),
        migrations.AlterUniqueTogether(
            name="leaveallocation",
            unique_together={("user", "contract")},
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="days_per_week",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="leaveallocation",
            index=models.Index(fields=["user"], name="employee_le_user_id_92a878_idx"),
        ),
        migrations.RemoveField(
            model_name="leaveallocation",
            name="year",
        ),
    ]
