# Generated by Django 5.2.8 on 2026-01-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_leaveallocation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="default_week_days",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="employeecontract",
            name="days_per_week",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
