# Generated by Django 5.2.8 on 2026-02-03 11:52
from django.db import migrations


def copy_supervisor_to_supervisors(apps, schema_editor):
    """Copy data from supervisor ForeignKey to supervisors ManyToMany"""
    LeaveRequest = apps.get_model('employee', 'LeaveRequest')
    
    migrated_count = 0
    skipped_count = 0
    
    for leave_request in LeaveRequest.objects.all():
        if leave_request.supervisor:
            # Add the supervisor to the supervisors ManyToMany field
            leave_request.supervisors.add(leave_request.supervisor)
            migrated_count += 1
            
        else:
            skipped_count += 1
    
    print(f"✓ Successfully migrated {migrated_count} supervisor relationships")
    print(f"⊘ Skipped {skipped_count} leave requests with no supervisor")


def reverse_copy_supervisor(apps, schema_editor):
    """Reverse migration: copy first supervisor back to supervisor field"""
    LeaveRequest = apps.get_model('employee', 'LeaveRequest')
    
    reversed_count = 0
    
    for leave_request in LeaveRequest.objects.all():
        first_supervisor = leave_request.supervisors.first()
        if first_supervisor:
            leave_request.supervisor = first_supervisor
            leave_request.save(update_fields=['supervisor'])
            reversed_count += 1
    
    print(f"✓ Reversed {reversed_count} supervisor relationships")


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_leaverequest_supervisors_and_more"),
    ]

    operations = [
        migrations.RunPython(
            copy_supervisor_to_supervisors,
            reverse_copy_supervisor
        ),
    ]