# Generated by Django 5.2.8 on 2026-01-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_employeecontract_default_week_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="contract_months",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
