# Generated by Django 5.2.8 on 2026-01-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_employeecontract_contract_months"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeecontract",
            name="fte_ratio",
        ),
        migrations.RemoveField(
            model_name="leaveallocation",
            name="carryforward_expiry_date",
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="entitled_leave",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total annual leave days entitled under this contract",
                max_digits=6,
            ),
        ),
    ]
