# Generated by Django 5.2.8 on 2026-01-13 07:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_remove_employeecontract_fte_ratio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("annual_days", models.DecimalField(decimal_places=2, default=25, max_digits=6)),
                ("sick_days", models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ("maternity_days", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("paternity_days", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "compassionate_days",
                    models.DecimalField(decimal_places=2, default=5, max_digits=6),
                ),
                ("study_days", models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                (
                    "applies_to_gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        help_text="Leave this blank if applies to all genders",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "leave_group",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-start_date", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="leaverequest",
            old_name="notes",
            new_name="details",
        ),
        migrations.RenameField(
            model_name="leaverequest",
            old_name="reason",
            new_name="supervisor_notes",
        ),
        migrations.RenameIndex(
            model_name="leaverequest",
            new_name="leave_reque_user_id_598dad_idx",
            old_name="employee_le_user_id_148d73_idx",
        ),
        migrations.RenameIndex(
            model_name="leaverequest",
            new_name="leave_reque_start_d_5cfac9_idx",
            old_name="employee_le_start_d_2e4886_idx",
        ),
        migrations.RemoveField(
            model_name="employeecontract",
            name="entitled_leave",
        ),
        migrations.RemoveField(
            model_name="employeecontract",
            name="renewed_from",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="leave_type_other",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="num_days",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="programme_manager_approved_by",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="supervisors",
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="entitled_leave_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override calculated leave entitlement for this specific contract",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="payroll_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="position",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="annual_forfeited",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="days_requested",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Number of leave days (can be fractional for half days)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor assigned to approve this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_requests_to_approve",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employeecontract",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("internship", "Internship"),
                    ("fixed_term_locum", "Fixed Term (Locum Basis)"),
                    ("fte", "FTE (Full-Time Equivalent)"),
                    ("annual", "Annual Contract"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="employeecontract",
            name="days_per_week",
            field=models.IntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="employeecontract",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="holiday_type",
            field=models.CharField(
                choices=[
                    ("public_national", "Public Holiday (National)"),
                    ("public_global", "Public Holiday (Global)"),
                    ("administrative", "Administrative Holiday"),
                    ("weekoff", "Week Off"),
                    ("other", "Other"),
                ],
                default="public_national",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leaveallocation",
            name="contract",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_allocations",
                to="employee.employeecontract",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leave_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="programme_manager_approved",
            field=models.BooleanField(
                default=False, help_text="Whether programme manager has approved"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="programme_manager_approved_at",
            field=models.DateTimeField(
                blank=True, help_text="Date when programme manager approved", null=True
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["supervisor", "status"], name="leave_reque_supervi_a12f45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["leave_type", "status"], name="leave_reque_leave_t_a7383a_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="leaverequest",
            table="leave_request",
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="leave_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave entitlement group for this contract",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="employee.leavegroup",
            ),
        ),
        migrations.AddIndex(
            model_name="employeecontract",
            index=models.Index(fields=["payroll_number"], name="employee_co_payroll_e53def_idx"),
        ),
    ]
