# Generated by Django 5.2.8 on 2026-01-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_leavegroup_alter_leaverequest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
