# Generated by Django 5.2.8 on 2026-01-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0007_alter_leaverequest_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="is_expired",
            field=models.BooleanField(default=True),
        ),
    ]
