# Generated by Django 5.2.8 on 2026-01-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_employeecontract_is_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeecontract",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
