# Generated by Django 5.2.8 on 2026-01-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_alter_employeecontract_is_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leave_requests",
                to="employee.employeecontract",
            ),
        ),
        migrations.DeleteModel(
            name="LeaveAllocation",
        ),
    ]
