# Generated by Django 5.2.8 on 2026-01-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_leaverequest_contract_delete_leaveallocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeecontract",
            name="position",
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="annual_carried_forward",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Annual leave days carried forward from previous leave year",
                max_digits=6,
            ),
        ),
    ]
