# Generated by Django 5.2.8 on 2026-01-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_remove_employeecontract_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeecontract",
            name="entitled_leave_override",
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="annual_leave_used",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Annual leave days already used before system tracking",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="employeecontract",
            name="sick_leave_used",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Sick leave days already used before system tracking",
                max_digits=6,
            ),
        ),
    ]
