# Generated by Django 5.2.8 on 2026-01-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0012_remove_employeecontract_entitled_leave_override_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="fte_percentage",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="fte percentage", max_digits=6
            ),
        ),
    ]
