# Generated by Django 5.2.8 on 2026-01-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0013_employeecontract_fte_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeecontract",
            name="days_per_week",
        ),
        migrations.RemoveField(
            model_name="employeecontract",
            name="default_week_days",
        ),
    ]
