# Generated by Django 5.2.8 on 2026-01-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0014_remove_employeecontract_days_per_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="default_week_days",
            field=models.IntegerField(default=5),
        ),
    ]
