# Generated by Django 5.2.8 on 2026-01-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0015_employeecontract_default_week_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeecontract",
            name="fte_percentage",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="fte percentage proportion", max_digits=6
            ),
        ),
    ]
