# Generated by Django 5.2.8 on 2026-01-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0016_alter_employeecontract_fte_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="is_forfeited",
            field=models.BooleanField(default=False),
        ),
    ]
