# Generated by Django 5.2.8 on 2025-12-16 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("priority", models.CharField(blank=True, max_length=20, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("progress", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "mint_project",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestones",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proj_milestones",
                        to="mint.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proj_Milestone",
                "verbose_name_plural": "Proj_Milestones",
                "db_table": "proj_mint_milestone",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("document_type", models.CharField(blank=True, max_length=50, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="projects/documents/")),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("external_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="mint.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_project_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Document",
                "verbose_name_plural": "Project Documents",
                "db_table": "mint_project_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RACIAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "raci_role",
                    models.CharField(
                        choices=[
                            ("R", "Responsible"),
                            ("A", "Accountable"),
                            ("C", "Consulted"),
                            ("I", "Informed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raci_assignments",
                        to="mint.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_raci_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RACI Assignment",
                "verbose_name_plural": "RACI Assignments",
                "db_table": "p_raci_assignment",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("progress", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="mint.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "db_table": "mint_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="tasks/attachments/")),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="mint.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Attachment",
                "verbose_name_plural": "Task Attachments",
                "db_table": "mint_task_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="mint.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Comment",
                "verbose_name_plural": "Task Comments",
                "db_table": "mint_task_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskRACIAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "raci_role",
                    models.CharField(
                        choices=[
                            ("R", "Responsible"),
                            ("A", "Accountable"),
                            ("C", "Consulted"),
                            ("I", "Informed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raci_assignments",
                        to="mint.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_raci_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task RACI Assignment",
                "verbose_name_plural": "Task RACI Assignments",
                "db_table": "mint_task_raci_assignment",
            },
        ),
        migrations.CreateModel(
            name="LeaveAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, help_text="Job position/title", max_length=100, null=True
                    ),
                ),
                ("year", models.IntegerField(default=2025)),
                ("annual_leave_days", models.IntegerField(default=0)),
                ("annual_used", models.IntegerField(default=0)),
                ("annual_left", models.IntegerField(default=0)),
                ("sick_leave_days", models.IntegerField(default=10)),
                ("sick_used", models.IntegerField(default=0)),
                ("maternity_leave_days", models.IntegerField(default=0)),
                ("maternity_used", models.IntegerField(default=0)),
                ("paternity_leave_days", models.IntegerField(default=0)),
                ("paternity_used", models.IntegerField(default=0)),
                ("compassionate_leave_days", models.IntegerField(default=0)),
                ("compassionate_used", models.IntegerField(default=0)),
                ("study_leave_days", models.IntegerField(default=0)),
                ("study_used", models.IntegerField(default=0)),
                ("other_leave_days", models.IntegerField(default=0)),
                ("other_used", models.IntegerField(default=0)),
                ("carryover_expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mint_leave_allocation",
                "ordering": ["-year"],
                "indexes": [
                    models.Index(fields=["user"], name="mint_leave__user_id_567858_idx"),
                    models.Index(fields=["user", "year"], name="mint_leave__user_id_8e5a3b_idx"),
                ],
                "unique_together": {("user", "year")},
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Job position/title of the employee",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("compassionate", "Compassionate Leave"),
                            ("study", "Study Leave"),
                            ("other", "Other (Specify)"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                (
                    "leave_type_other",
                    models.CharField(
                        blank=True,
                        help_text="Specify if leave_type is 'Other'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("num_days", models.IntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "programme_manager_approved",
                    models.BooleanField(
                        default=False, help_text="Whether programme manager has approved"
                    ),
                ),
                (
                    "programme_manager_approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Date when programme manager approved", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor/Manager who approved the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programme_manager_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Programme Manager approval (can be after leave has been taken)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programme_manager_approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Direct supervisor(s) of the employee",
                        related_name="supervised_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "mint_leave_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="mint_leave__user_id_809ab8_idx"),
                    models.Index(
                        fields=["start_date", "end_date"], name="mint_leave__start_d_849a09_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner", "status"], name="mint_projec_owner_i_3def9c_idx"),
        ),
        migrations.AddIndex(
            model_name="raciassignment",
            index=models.Index(
                fields=["project", "raci_role"], name="p_raci_assi_project_a8f3d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="raciassignment",
            index=models.Index(
                fields=["user", "raci_role"], name="p_raci_assi_user_id_26e32a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["project", "status"], name="mint_task_project_826b8b_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["priority"], name="mint_task_priorit_e4a512_idx"),
        ),
        migrations.AddIndex(
            model_name="taskraciassignment",
            index=models.Index(
                fields=["task", "raci_role"], name="mint_task_r_task_id_22d7d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskraciassignment",
            index=models.Index(
                fields=["user", "raci_role"], name="mint_task_r_user_id_b96fd0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskraciassignment",
            unique_together={("task", "user", "raci_role")},
        ),
    ]
