# Generated by Django 5.2.8 on 2026-01-10 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, help_text="Job position/title", max_length=100, null=True
                    ),
                ),
                ("year", models.IntegerField(default=2025)),
                ("annual_leave_days", models.IntegerField(default=0)),
                ("annual_used", models.IntegerField(default=0)),
                ("annual_left", models.IntegerField(default=0)),
                ("sick_leave_days", models.IntegerField(default=10)),
                ("sick_used", models.IntegerField(default=0)),
                ("maternity_leave_days", models.IntegerField(default=0)),
                ("maternity_used", models.IntegerField(default=0)),
                ("paternity_leave_days", models.IntegerField(default=0)),
                ("paternity_used", models.IntegerField(default=0)),
                ("compassionate_leave_days", models.IntegerField(default=0)),
                ("compassionate_used", models.IntegerField(default=0)),
                ("study_leave_days", models.IntegerField(default=0)),
                ("study_used", models.IntegerField(default=0)),
                ("other_leave_days", models.IntegerField(default=0)),
                ("other_used", models.IntegerField(default=0)),
                ("carryover_expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mint_leave_allocation",
                "ordering": ["-year"],
                "indexes": [
                    models.Index(fields=["user"], name="mint_leave__user_id_567858_idx"),
                    models.Index(fields=["user", "year"], name="mint_leave__user_id_8e5a3b_idx"),
                ],
                "unique_together": {("user", "year")},
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Job position/title of the employee",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual Leave"),
                            ("sick", "Sick Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("compassionate", "Compassionate Leave"),
                            ("study", "Study Leave"),
                            ("other", "Other (Specify)"),
                        ],
                        default="annual",
                        max_length=20,
                    ),
                ),
                (
                    "leave_type_other",
                    models.CharField(
                        blank=True,
                        help_text="Specify if leave_type is 'Other'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("num_days", models.IntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "programme_manager_approved",
                    models.BooleanField(
                        default=False, help_text="Whether programme manager has approved"
                    ),
                ),
                (
                    "programme_manager_approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Date when programme manager approved", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor/Manager who approved the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programme_manager_approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Programme Manager approval (can be after leave has been taken)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programme_manager_approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Direct supervisor(s) of the employee",
                        related_name="supervised_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "mint_leave_request",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="mint_leave__user_id_809ab8_idx"),
                    models.Index(
                        fields=["start_date", "end_date"], name="mint_leave__start_d_849a09_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                (
                    "duration_template",
                    models.CharField(
                        blank=True, help_text="e.g., '3 months'", max_length=100, null=True
                    ),
                ),
                (
                    "sprint_goals",
                    models.TextField(
                        blank=True, help_text="Describe the main objectives", null=True
                    ),
                ),
                (
                    "expected_deliverables",
                    models.TextField(blank=True, help_text="List the key deliverables", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sprint",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"], name="sprint_start_d_b0de07_idx"
                    ),
                    models.Index(
                        fields=["is_active", "department"], name="sprint_is_acti_19d35b_idx"
                    ),
                ],
            },
        ),
    ]
