# Generated by Django 5.2.8 on 2025-12-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
