# Generated by Django 5.2.8 on 2025-12-03 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mint", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaveallocation",
            options={"ordering": ["-year"]},
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="annual_carryover",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="carryover_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaveallocation",
            name="annual_leave_days",
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="leaveallocation",
            name="sick_leave_days",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="leaveallocation",
            name="special_leave_days",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="leaveallocation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_allocations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
