# Generated by Django 5.2.8 on 2025-12-03 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mint", "0002_alter_leaveallocation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="leaveallocation",
            name="mint_leave__user_id_8e5a3b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="leaveallocation",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="leaveallocation",
            name="year",
            field=models.IntegerField(default=2025),
        ),
        migrations.AddIndex(
            model_name="leaveallocation",
            index=models.Index(fields=["user"], name="mint_leave__user_id_567858_idx"),
        ),
    ]
