# Generated by Django 5.2.8 on 2026-01-06 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mint", "0002_milestonecomment_projectcomment_projectnote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("year", models.IntegerField()),
                (
                    "is_recurring",
                    models.BooleanField(default=False, help_text="Recurs annually on same date"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Public Holiday",
                "verbose_name_plural": "Public Holidays",
                "db_table": "mint_public_holiday",
                "ordering": ["date"],
                "indexes": [
                    models.Index(fields=["date", "year"], name="mint_public_date_eb65b8_idx")
                ],
                "unique_together": {("date", "year")},
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("leave", "Leave"),
                            ("project_deadline", "Project Deadline"),
                            ("milestone", "Milestone"),
                            ("public_holiday", "Public Holiday"),
                            ("weekend", "Weekend"),
                            ("meeting", "Meeting"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Public holidays, weekends visible to all"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, help_text="Hex color code for display", max_length=7, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="mint.leaverequest",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="mint.milestones",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="mint.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with this event (for leaves, personal events)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendar Event",
                "verbose_name_plural": "Calendar Events",
                "db_table": "mint_calendar_event",
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"], name="mint_calend_start_d_764e4a_idx"
                    ),
                    models.Index(
                        fields=["event_type", "is_public"], name="mint_calend_event_t_e981ca_idx"
                    ),
                    models.Index(
                        fields=["user", "start_date"], name="mint_calend_user_id_e9605e_idx"
                    ),
                ],
            },
        ),
    ]
