# Generated by Django 5.2.8 on 2025-12-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mint", "0003_remove_leaveallocation_mint_leave__user_id_8e5a3b_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaveallocation",
            old_name="annual_carryover",
            new_name="annual_left",
        ),
        migrations.RenameField(
            model_name="leaveallocation",
            old_name="special_used",
            new_name="other_leave_days",
        ),
        migrations.RemoveField(
            model_name="leaveallocation",
            name="special_leave_days",
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="other_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="leaveallocation",
            name="annual_leave_days",
            field=models.IntegerField(default=0),
        ),
    ]
