# Generated by Django 5.2.8 on 2025-12-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mint", "0003_alter_project_priority_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="priority",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
