# Generated by Django 5.2.8 on 2026-01-07 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mint", "0003_publicholiday_calendarevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="comment_notify",
            field=models.BooleanField(
                default=True,
                help_text="Send notifications when comments are added to project reviews",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="notify_supervisor",
            field=models.BooleanField(
                default=False,
                help_text="Notify supervisor/informed users when project status changes",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_link",
            field=models.URLField(
                blank=True,
                help_text="Link to project resources, documentation, or repository",
                max_length=500,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProjectReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("on_review", "On Review"),
                            ("successfully_reviewed", "Successfully Reviewed"),
                            ("changes_requested", "Changes Requested"),
                        ],
                        default="pending",
                        help_text="Current status of the review",
                        max_length=50,
                    ),
                ),
                (
                    "review_summary",
                    models.TextField(
                        blank=True, help_text="Overall review summary and feedback", null=True
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the project was submitted for review",
                        null=True,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the review was completed", null=True
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, help_text="Mark project review as closed/completed"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when project review was closed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_reviews_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        help_text="The project being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_review",
                        to="mint.project",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary reviewer (typically supervisor/informed user)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_reviews_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Review",
                "verbose_name_plural": "Project Reviews",
                "db_table": "project_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectReviewComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("comment", models.TextField(help_text="Comment content")),
                (
                    "attachment_links",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of URLs for attachments/references",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False, help_text="Mark if this comment/issue has been resolved"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent comment for threaded discussions",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="mint.projectreviewcomment",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        help_text="The review this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="mint.projectreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who made the comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Review Comment",
                "verbose_name_plural": "Project Review Comments",
                "db_table": "project_review_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="projectreview",
            index=models.Index(
                fields=["project", "status"], name="project_rev_project_1b4238_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreview",
            index=models.Index(
                fields=["reviewer", "status"], name="project_rev_reviewe_8788e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreview",
            index=models.Index(
                fields=["status", "submitted_at"], name="project_rev_status_0b1b32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreviewcomment",
            index=models.Index(
                fields=["review", "created_at"], name="project_rev_review__84eb1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreviewcomment",
            index=models.Index(
                fields=["user", "created_at"], name="project_rev_user_id_08c8f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreviewcomment",
            index=models.Index(fields=["is_resolved"], name="project_rev_is_reso_2ba9c5_idx"),
        ),
    ]
