# Generated by Django 5.2.8 on 2025-12-04 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mint", "0004_rename_annual_carryover_leaveallocation_annual_left_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveallocation",
            name="compassionate_leave_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="compassionate_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="maternity_leave_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="maternity_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="paternity_leave_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="paternity_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="position",
            field=models.CharField(
                blank=True, help_text="Job position/title", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="study_leave_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaveallocation",
            name="study_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="leave_type_other",
            field=models.CharField(
                blank=True, help_text="Specify if leave_type is 'Other'", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="position",
            field=models.CharField(
                blank=True,
                help_text="Job position/title of the employee",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="programme_manager_approved",
            field=models.BooleanField(
                default=False, help_text="Whether programme manager has approved"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="programme_manager_approved_at",
            field=models.DateTimeField(
                blank=True, help_text="Date when programme manager approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="programme_manager_approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Programme Manager approval (can be after leave has been taken)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programme_manager_approved_leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor/Manager who approved the request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("annual", "Annual Leave"),
                    ("sick", "Sick Leave"),
                    ("maternity", "Maternity Leave"),
                    ("paternity", "Paternity Leave"),
                    ("compassionate", "Compassionate Leave"),
                    ("study", "Study Leave"),
                    ("other", "Other (Specify)"),
                ],
                default="annual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="supervisors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Direct supervisor(s) of the employee",
                related_name="supervised_leave_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaveallocation",
            unique_together={("user", "year")},
        ),
        migrations.AddIndex(
            model_name="leaveallocation",
            index=models.Index(fields=["user", "year"], name="mint_leave__user_id_8e5a3b_idx"),
        ),
    ]
