# Generated by Django 5.2.8 on 2026-01-07 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mint", "0005_project_supervisor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="supervisor",
        ),
        migrations.AddField(
            model_name="project",
            name="supervisors",
            field=models.ManyToManyField(
                blank=True,
                help_text="The supervisors/coordinators responsible for this project",
                related_name="supervised_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Project Supervisors",
            ),
        ),
    ]
