# Generated by Django 5.2.8 on 2025-12-02 07:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="users/profiles/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_token", models.CharField(blank=True, max_length=255, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("account_locked_until", models.DateTimeField(blank=True, null=True)),
                ("force_password_change", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to="accounts.customuser",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="custom_users",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_users",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "accounts_custom_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenBlacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_jti", models.CharField(db_index=True, max_length=255, unique=True)),
                ("token_type", models.CharField(max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_tokens",
                        to="accounts.customuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Blacklist",
                "verbose_name_plural": "Token Blacklists",
                "db_table": "accounts_token_blacklist",
            },
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="accounts_cu_email_2281ee_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["username"], name="accounts_cu_usernam_304c6f_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["status"], name="accounts_cu_status_b63c19_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenblacklist",
            index=models.Index(fields=["token_jti"], name="accounts_to_token_j_b4961f_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenblacklist",
            index=models.Index(fields=["user"], name="accounts_to_user_id_d3929e_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenblacklist",
            index=models.Index(fields=["expires_at"], name="accounts_to_expires_384bdc_idx"),
        ),
    ]
