# Generated by Django 5.2.8 on 2026-01-15 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="users/profiles/"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin (Director/PI)"),
                            ("office_admin", "Office Admin (Manager)"),
                            ("supervisor", "Supervisor (Coordinator)"),
                            ("staff", "Staff (Researcher)"),
                        ],
                        db_index=True,
                        default="staff",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                (
                    "position",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_external_member", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_token", models.CharField(blank=True, max_length=255, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("account_locked_until", models.DateTimeField(blank=True, null=True)),
                ("force_password_change", models.BooleanField(default=False)),
                ("is_invited", models.BooleanField(default=False)),
                ("invite_token", models.UUIDField(blank=True, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("invite_expires_at", models.DateTimeField(blank=True, null=True)),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to="accounts.customuser",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="custom_users", to="auth.group"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_users",
                        to="accounts.customuser",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="custom_users", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "accounts_custom_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TokenBlacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_jti", models.CharField(db_index=True, max_length=255, unique=True)),
                ("token_type", models.CharField(max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("blacklisted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklisted_tokens",
                        to="accounts.customuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Blacklist",
                "verbose_name_plural": "Token Blacklists",
                "db_table": "accounts_token_blacklist",
            },
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="accounts_cu_email_2281ee_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["username"], name="accounts_cu_usernam_304c6f_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["role"], name="accounts_cu_role_e15487_idx"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["status"], name="accounts_cu_status_b63c19_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenblacklist",
            index=models.Index(fields=["token_jti"], name="accounts_to_token_j_b4961f_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenblacklist",
            index=models.Index(fields=["user"], name="accounts_to_user_id_d3929e_idx"),
        ),
        migrations.AddIndex(
            model_name="tokenblacklist",
            index=models.Index(fields=["expires_at"], name="accounts_to_expires_384bdc_idx"),
        ),
    ]
