# Generated by Django 5.2.8 on 2026-02-05 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emaillog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=128)),
                ("device_name", models.CharField(blank=True, max_length=100)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("location_info", models.CharField(blank=True, max_length=200)),
                ("is_trusted", models.BooleanField(default=False)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verification_token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("verification_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_trusted_device",
                "ordering": ["-last_used_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "device_id"], name="accounts_tr_user_id_f25265_idx"
                    ),
                    models.Index(
                        fields=["verification_token"], name="accounts_tr_verific_2ed41e_idx"
                    ),
                ],
                "unique_together": {("user", "device_id")},
            },
        ),
    ]
