# Generated by Django 5.2.8 on 2026-02-05 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_trusteddevice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trusteddevice",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="trusteddevice",
            name="accounts_tr_user_id_f25265_idx",
        ),
        migrations.RemoveIndex(
            model_name="trusteddevice",
            name="accounts_tr_verific_2ed41e_idx",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="last_used_at",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="location_info",
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="user_agent",
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="failed_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="last_failed_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="device_id",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="is_trusted",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="trusteddevice",
            name="verification_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="trusteddevice",
            table=None,
        ),
    ]
