# Generated by Django 5.2.8 on 2025-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_role_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_external_member",
            field=models.BooleanField(default=False),
        ),
    ]
