# Generated by Django 5.2.8 on 2026-02-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_trusteddevice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trusteddevice",
            options={"ordering": ["-last_used_at"]},
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="browser",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="last_used_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="os",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trusteddevice",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
    ]
