# Generated by Django 5.2.8 on 2025-12-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
