# Generated by Django 5.2.8 on 2026-02-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_loginattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
