# Generated by Django 5.2.8 on 2026-02-06 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_loginattempt_payload"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_leave_approvals", models.BooleanField(default=True)),
                ("email_activities", models.BooleanField(default=True)),
                ("email_reviews", models.BooleanField(default=True)),
                ("email_contracts", models.BooleanField(default=True)),
                (
                    "activity_due_alert_days",
                    models.IntegerField(
                        choices=[
                            (1, "1 Day Before"),
                            (3, "3 Days Before"),
                            (7, "7 Days Before"),
                            (14, "14 Days Before"),
                        ],
                        default=3,
                        help_text="Days before deadline to send alert",
                    ),
                ),
                (
                    "contract_expiry_alert_days",
                    models.IntegerField(
                        choices=[
                            (1, "1 Day Before"),
                            (3, "3 Days Before"),
                            (7, "7 Days Before"),
                            (14, "14 Days Before"),
                        ],
                        default=14,
                        help_text="Days before contract expiry to send alert",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preference",
            },
        ),
    ]
