# Generated by Django 5.2.8 on 2025-12-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customuser_invite_expires_at_customuser_invite_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
