# Generated by Django 5.2.8 on 2026-02-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_emaillog_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="sender",
            field=models.CharField(default="raci@cema.africa", max_length=255),
        ),
    ]
